"""Add active_term to school_setting

Revision ID: c25994583577
Revises: 
Create Date: 2026-09-09 03:13:21.043557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c25994583577'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school_setting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_term', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school_setting', schema=None) as batch_op:
        batch_op.drop_column('active_term')

    # ### end Alembic commands ###
